### ISSUE TITLE
Crash on iPhone SE 2016 with IOS 13.4.1

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#2768]
Using lastest air sdk 50.2.3.3 and latest x code 14.3.1
crash log is here
[crash-2023-08-16-093209.ips.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12356954/crash-2023-08-16-093209.ips.zip)
on another iOS the app works fine

ipa is here
https://easyupload.io/4hzsvc
any idea?

**Comment by shaymolho** [comment]
@ajwfrost @marchbold

**Comment by shaymolho** [comment]
what is the solution?
my anes are attached here
[project-apm.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12368674/project-apm.zip)

**Comment by ajwfrost** [comment]
Hi

Can you please try re-packaging using the ADT version from the attached (this can be copied over the latest AIR SDK, in the "lib" folder, once it's unzipped..)

I am hoping that the re-ordering of the linker commands will mean that the symbols are picked up from the Swift foundation library now, rather than the framework...

It would be good if you're also able to have logging enabled when building, either via an adt.log file or via the AIR SDK Manager "troubleshooting" tab, so that we can see the updated ld64 command line...?

thanks

   Andrew

[adt.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12371772/adt.zip)

**Comment by shaymolho** [comment]
Hi @ajwfrost 
This still doesn't work
attached adt.log
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/12387711/adt.log)

**Comment by ajwfrost** [comment]
Hi

The linking line has `-lSwiftCompat` but I would also expect to see `-lswiftCoreFoundation` in order to get the right symbols included... are you able to add that in to the ANE?

thanks

**Comment by shaymolho** [comment]
Hi
how to do that? 
in the final linking line you expect only
`-lswiftCoreFoundation ` or also 
`-lSwiftCompat `  as well?

**Comment by marchbold** [comment]
@shaymolho Are you using our ANEs? Let me know which ones and I'll add this flag into it for you.

**Comment by ajwfrost** [comment]
I would assume both libraries are needed here.

Is the swift code (that's in these ANEs) part of some third party components? If not, do we know whether there's usage of something like the `CocoaError` structure? https://swiftinit.org/reference/5.6.1/foundation/cocoaerror

I'm wondering whether this is behind that missing symbol... (hoping we could perhaps set up a reproduction of this scenario here!)

thanks

**Comment by shaymolho** [comment]
@marchbold yes, u can see the app descriptor in a few comments above
i attached it again here
[my-app-ios-decriptor.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12393527/my-app-ios-decriptor.zip)

**Comment by shaymolho** [comment]
the ANE that adds the lSwiftCompat is

**Comment by marchbold** [comment]
Yep, I'll get a test version of it built this morning.

**Comment by marchbold** [comment]
This build has the flag: [com.google.firebase.core.ane.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12403866/com.google.firebase.core.ane.zip)

**Comment by shaymolho** [comment]
did u change anything else or just added the flag to platform,xml? because i built with manually adding this flag (adt.log attached) and still crashes:

**Comment by marchbold** [comment]
I just added the additional flag.

**Comment by shaymolho** [comment]
i see it in the log:
`ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch arm64 -L"/Users/aviv/flash_air_sdk_50/lib/aot/stub" -sdk_version 16.4 -F"/Users/aviv/flash_air_sdk_50/lib/aot/stub" -L"/Users/aviv/flash_air_sdk_50/lib/aot/lib" -o "../aot4384681983792917504.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/aviv/flash_air_sdk_50/lib/aot/lib/libRuntimeHMAOT.arm-air.a" "/Users/aviv/flash_air_sdk_50/lib/aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lz -lobjc -lclang_rt.ios -weak_framework AppTrackingTransparency -framework AdSupport -w -exported_symbol _IDFAExtInitializer -exported_symbol _IDFAExtFinalizer "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/0fcd7dcb-6530-4448-89e7-9718900f7447" -framework "FBSDKLoginKit" -exported_symbol _FacebookLoginExtInitializer -exported_symbol _FacebookLoginExtFinalizer "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/91f14876-21f0-4778-8ef5-318201eacdfd" -framework "Bolts" -exported_symbol _BoltsExtInitializer -exported_symbol _BoltsExtFinalizer -rpath /usr/lib/swift -lswiftCoreFoundation -lSwiftCompat -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/0bd551ca-35d5-42fc-af38-9757053a7519" -framework "FBLPromises" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesSwift" -framework "FirebaseSharedSwift" -exported_symbol _firebasecoreExtInitializer -exported_symbol _firebasecoreExtFinalizer -ObjC -lz -lsqlite3 -w "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/70d43a62-c994-4109-ab71-62b3a35abcbb" -framework "FirebaseCrashlytics" -framework "FirebaseSessions" -exported_symbol _FirebaseCrashlyticsExtInitializer -exported_symbol _FirebaseCrashlyticsExtFinalizer -framework UserNotifications -framework AddressBook -exported_symbol _PushNotificationsExtInitializer -exported_symbol _PushNotificationsExtFinalizer -lclang_rt.ios -ObjC -weak_framework UserNotifications -w "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/4af94db6-1cd3-443a-952c-d0e573ba1428" -framework "CoreNativeExtension" -exported_symbol _CoreExtInitializer -exported_symbol _CoreExtFinalizer -rpath @executable_path/Frameworks -weak_framework Social -framework AuthenticationServices -framework SafariServices -framework Accelerate -framework CoreMotion -framework Accounts -framework Security "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/b7836dd8-ecf6-4376-8e8a-8ba8c4ca546e" -framework "FBAEMKit" -framework "FBSDKCoreKit" -framework "FBSDKCoreKit_Basics" -exported_symbol _FacebookCoreExtInitializer -exported_symbol _FacebookCoreExtFinalizer -framework StoreKit -exported_symbol _InAppBillingExtInitializer -exported_symbol _InAppBillingExtFinalizer -lclang_rt.ios -liconv -framework AdSupport -framework iAd "-L/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/ce9713eb-f86f-4679-9f30-9afa5d9fc578" "-lAppsFlyerLib" -exported_symbol _AFExtensionInitializer -w -exported_symbol _ApplicationExtInitializer -exported_symbol _ApplicationExtFinalizer -framework Security -liconv -lz -w -exported_symbol _ZipUtilsExtInitializer -exported_symbol _ZipUtilsExtFinalizer -framework AuthenticationServices -exported_symbol _AppleSignInExtInitializer -exported_symbol _AppleSignInExtFinalizer -framework AVFoundation -framework AudioToolbox -framework MediaPlayer -w -exported_symbol _VolumeExtInitializer -exported_symbol _VolumeExtFinalizer -framework CoreHaptics -w -exported_symbol _VibrationExtInitializer -exported_symbol _VibrationExtFinalizer -framework MessageUI -framework Accounts -framework Social -framework ImageIO -w -exported_symbol _ShareExtInitializer -exported_symbol _ShareExtFinalizer "-F/var/folders/56/j5mpmhm10jlbfcjg5fx6x4h80000gn/T/301b2b10-caa8-44a8-9501-384e9825e2de" -framework "FirebaseAnalytics" -exported_symbol _FirebaseExtInitializer -exported_symbol _FirebaseExtFinalizer -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -filelist "/Users/aviv/slota-svn/15.0/webapp/flex/slotagram-mobile-boot2/target/AOTBuildOutput4425336874712814990.tmp/OBJFilesList.txt" -ios_version_min 12.0`
search for _lswiftCoreFoundation_

**Comment by marchbold** [comment]
Ah there are two builds in the log, I only looked at the first one which doesn't have it.

**Comment by shaymolho** [comment]
[crash-log.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12406325/crash-log.zip)
this is the crash, the other one is device

**Comment by shaymolho** [comment]
adding the flag `-lswiftCoreFoundation` didn't solve the problem with the suggested adt.jar.
adt.log:

**Comment by ajwfrost** [comment]
Hmm.. so despite that, it's still got the missing symbol:
```
expected in '/System/Library/Frameworks/Foundation.framework/Foundation'
```

Will need to check a bit further - we can just exclude it from the Foundation stub, but we'd likely have a number of symbols that need to change here..

thanks

**Comment by sthompson-crestron** [comment]
Trying to help, I did a build the  50.2.3 SDK and with the adt.jar posted here.  In both cases, when running the application on 15.7.8 I got the following error:

dyld[1163]: Symbol not found: (_$s10Foundation4DataV15withUnsafeBytesyxxSWKXEKlF)
  Referenced from: '/private/var/containers/Bundle/Application/372BA38F-28BF-413E-A524-E80A98A26965/andros.app/CA_dbg_phone'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Foundation'

I will have to investigate how to generate a log file out of adt as my commands are wrapped up in build scripts that I'll have to poke around in.

**Comment by sthompson-crestron** [comment]
I added `-lswiftFoundation` to the XML file for my build and it now runs without issue on 15.7.8.  I also have `SwiftCompat` on there too.

        <option>-lswiftFoundation</option>
        <option>-lSwiftCompat</option>

**Comment by ajwfrost** [comment]
Thanks @sthompson-crestron  - maybe I'd suggested the wrong library when asking @marchbold  to add `-lswiftCoreFoundation` into the ANE, maybe it should be `-lswiftFoundation` instead..!

FYI, with the recent AIR SDKs, you can just have the AIR SDK Manager running at the "Troubleshooting" tab, and then ADT will automatically connect to it and dump out the debug log... (assuming your didn't block this when installing, macOS seems to give a warning about this..)

**Comment by sthompson-crestron** [comment]
OK.  I will google the "AIR SDK Manager" ;-)

**Comment by shaymolho** [comment]
Thanks @sthompson-crestron , it's working also for us
@marchbold can you please change the flag from
`-lswiftCoreFoundation` to `-lswiftFoundation` and upload to apm? after that i'll close this issue

**Comment by ajwfrost** [comment]
@shaymolho thanks for checking this -> are you able to also confirm whether or not you need the updated ADT.jar file that we posted here? It sounds like it may just be that we need to include `-lswiftFoundation` without having to change the command-line ordering....

thanks

**Comment by marchbold** [comment]
Here's another update including that additional library option

[com.google.firebase.core.v32.1.104.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12482301/com.google.firebase.core.v32.1.104.zip)

Let me know if this works and I'll get the update published.

**Comment by marchbold** [comment]
@ajwfrost This doesn't seem to work when packaging for the ios simulator. I'm getting 

```
ld: library not found for -lswiftFoundation
```

And without it I'm getting a list of missing symbols. 


<details>
<summary>adt.log</summary>

```
ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch x86_64 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk" -L/usr/lib -F"/System/Library/Frameworks" -L"/Users/marchbold/work/sdks/air/AIRSDK_50.2.3/lib/aot/lib" -o "../aot7708806804944014132.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/marchbold/work/sdks/air/AIRSDK_50.2.3/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a" -lc++ -lSystem -U ___darwin_check_fd_set_overflow -lz -lobjc -lclang_rt.ios -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -lclang_rt.ios -ObjC -weak_framework UserNotifications -w "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/539b6b32-62a8-474f-a3f5-b0f73224277b" -framework "CoreNativeExtension" -exported_symbol _CoreExtInitializer -exported_symbol _CoreExtFinalizer -rpath /usr/lib/swift -lSwiftCompat -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/530dbb0b-5237-4761-92cb-4ada61d35039" -framework "FBLPromises" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesSwift" -framework "FirebaseSharedSwift" -exported_symbol _FirebaseCoreExtInitializer -exported_symbol _FirebaseCoreExtFinalizer -licucore -lz -lxml2 -lsqlite3 -lc++ -ObjC -w "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/c3021e94-137f-42ac-ab94-7e88d19c2fa5" -framework "FirebaseDatabase" -framework "FirebaseDatabaseSwift" -framework "leveldb-library" -exported_symbol _FirebaseDatabaseExtInitializer -exported_symbol _FirebaseDatabaseExtFinalizer "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/f671c410-9498-4661-96f2-5bb8bce0b6e4" -framework "FirebaseAnalytics" -exported_symbol _FirebaseExtInitializer -exported_symbol _FirebaseExtFinalizer -framework SafariServices -framework Security -ObjC -w "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/f4fbfafb-0ad3-49fc-ab27-bc9b3a83cf7d" -framework "FirebaseAppCheckInterop" -framework "FirebaseAuth" -framework "GTMSessionFetcher" -exported_symbol _FirebaseAuthExtInitializer -exported_symbol _FirebaseAuthExtFinalizer -filelist "/Users/marchbold/work/distriqt/extensions/extensions/firebase/source/extensions/database/example/starling/bin-debug/AOTBuildOutput1769536892830624896.tmp/OBJFilesList.txt" -platform_version ios-simulator 11.0 16.4
Undefined symbols for architecture x86_64:
  "_$s3Keys30KeyedDecodingContainerProtocolPTl", referenced from:
      _$s19FirebaseSharedSwift27_JSONKeyedDecodingContainer33_6D166423BA39F764DCB8915CD73AA0F1LLVyxGs05KeyedeF8ProtocolAAMc in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$s3Keys30KeyedEncodingContainerProtocolPTl", referenced from:
      _$s19FirebaseSharedSwift27_JSONKeyedEncodingContainer33_6D166423BA39F764DCB8915CD73AA0F1LLVyxGs05KeyedeF8ProtocolAAMc in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$s7ElementSTTl", referenced from:
      _$s20FirebaseCoreInternal10RingBufferVyxGSTAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s8Promises7PromiseC6reduce2on__ACyxGSo17OS_dispatch_queueC_qd__AFx_7ElementQyd__tKctSTRd__lFA2F_AJtXEfU_ in PromisesSwift(Promise+Reduce.o)
      l_objectdestroy in PromisesSwift(Promise+Reduce.o)
      _$s8Promises7PromiseC6reduce2on__ACyxGSo17OS_dispatch_queueC_qd__AFx_7ElementQyd__tKctSTRd__lFA2F_AJtXEfU_AFxKcfU_TA in PromisesSwift(Promise+Reduce.o)
  "_$s8AllCasess12CaseIterablePTl", referenced from:
      _$s20FirebaseCoreInternal10TimePeriodOs12CaseIterableAAMc in FirebaseCoreInternal(Heartbeat.o)
  "_$s8Dispatch0A13WorkItemFlagsVMa", referenced from:
      _$s20FirebaseCoreInternal16HeartbeatStorageC17readAndWriteAsync5usingyAA16HeartbeatsBundleVSgAHc_tF in FirebaseCoreInternal(HeartbeatStorage.o)
  "_$s8Dispatch0A13WorkItemFlagsVMn", referenced from:
      _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseCoreInternal(HeartbeatStorage.o)
  "_$s8Dispatch0A13WorkItemFlagsVs10SetAlgebraAAMc", referenced from:
      _$s20FirebaseCoreInternal16HeartbeatStorageC17readAndWriteAsync5usingyAA16HeartbeatsBundleVSgAHc_tF in FirebaseCoreInternal(HeartbeatStorage.o)
  "_$s8Dispatch0A3QoSV11unspecifiedACvgZ", referenced from:
      _$s20FirebaseCoreInternal16HeartbeatStorageC17readAndWriteAsync5usingyAA16HeartbeatsBundleVSgAHc_tF in FirebaseCoreInternal(HeartbeatStorage.o)
      _$s20FirebaseCoreInternal16HeartbeatStorageC2id7storageACSS_AA0E0_ptcfcTf4gnn_nTf4nen_nAA04FileE0C_Tg5 in FirebaseCoreInternal(HeartbeatStorage.o)
  "_$s8Dispatch0A3QoSVMa", referenced from:
      _$s20FirebaseCoreInternal16HeartbeatStorageC17readAndWriteAsync5usingyAA16HeartbeatsBundleVSgAHc_tF in FirebaseCoreInternal(HeartbeatStorage.o)
      _$s20FirebaseCoreInternal16HeartbeatStorageC2id7storageACSS_AA0E0_ptcfcTf4gnn_nTf4nen_nAA04FileE0C_Tg5 in FirebaseCoreInternal(HeartbeatStorage.o)
  "_$s8IteratorSTTl", referenced from:
      _$s20FirebaseCoreInternal10RingBufferVyxGSTAAMc in FirebaseCoreInternal(RingBuffer.o)
  "_$s8RawValueSYTl", referenced from:
      _$s20FirebaseCoreInternal10TimePeriodOSYAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSYAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
  "_$sBOWV", referenced from:
      _$s20FirebaseCoreInternal25_ObjC_HeartbeatControllerCMf in FirebaseCoreInternal(_ObjC_HeartbeatController.o)
      _$s20FirebaseCoreInternal23_ObjC_HeartbeatsPayloadCMf in FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal11FileStorageCMr in FirebaseCoreInternal(Storage.o)
      _$s8Promises7PromiseCMr in PromisesSwift(Promise.o)
  "_$sBbWV", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVMr in FirebaseCoreInternal(Heartbeat.o)
      _$s19FirebaseSharedSwift20_JSONDecodingStorage33_6D166423BA39F764DCB8915CD73AA0F1LLVMf in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift20_JSONEncodingStorage33_6D166423BA39F764DCB8915CD73AA0F1LLVMf in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sBi64_WV", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVMr in FirebaseCoreInternal(Heartbeat.o)
  "_$sBoWV", referenced from:
      _$s20FirebaseCoreInternal19HeartbeatControllerCMf in FirebaseCoreInternal(HeartbeatController.o)
      _$s20FirebaseCoreInternal16HeartbeatStorageCMf in FirebaseCoreInternal(HeartbeatStorage.o)
      _$s20FirebaseCoreInternal11FileStorageCMf in FirebaseCoreInternal(Storage.o)
      _$s20FirebaseCoreInternal19UserDefaultsStorageCMf in FirebaseCoreInternal(Storage.o)
      _$s19FirebaseSharedSwift0A11DataEncoderCMf in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift13__JSONEncoder33_6D166423BA39F764DCB8915CD73AA0F1LLCMf in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift24__JSONReferencingEncoder33_6D166423BA39F764DCB8915CD73AA0F1LLCMf in FirebaseSharedSwift(FirebaseDataEncoder.o)
      ...
  "_$sSD4KeysVMa", referenced from:
      _$sSD4KeysVySSyp_GMa in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSD4KeysVMn", referenced from:
      _symbolic _____ySSyp_G SD4KeysV in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSD4KeysVyxq__GSTsMc", referenced from:
      _$s19FirebaseSharedSwift27_JSONKeyedDecodingContainer33_6D166423BA39F764DCB8915CD73AA0F1LLV7allKeysSayxGvg in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSDMa", referenced from:
      _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGMa in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$sSDyS2SGMa in FirebaseDatabaseSwift(ServerTimestamp.o)
  "_$sSDMn", referenced from:
      _$sSDyxq_G19FirebaseSharedSwift36_JSONStringDictionaryEncodableMarker33_6D166423BA39F764DCB8915CD73AA0F1LLABSSRszSER_rlMc in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$sSDyxq_G19FirebaseSharedSwift36_JSONStringDictionaryDecodableMarker33_6D166423BA39F764DCB8915CD73AA0F1LLABSSRszSeR_rlMc in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSDyxq_GSEsSERzSER_rlMc", referenced from:
      _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGSDyxq_GSEsSERzSER_rlWl in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$sSDyS2SGSDyxq_GSEsSERzSER_rlWl in FirebaseDatabaseSwift(ServerTimestamp.o)
  "_$sSDyxq_GSesSeRzSeR_rlMc", referenced from:
      _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGSDyxq_GSesSeRzSeR_rlWl in FirebaseCoreInternal(HeartbeatsBundle.o)
  "_$sSE6encode2toys7Encoder_p_tKFTj", referenced from:
      _$s19FirebaseSharedSwift13__JSONEncoder33_6D166423BA39F764DCB8915CD73AA0F1LLC4box_ySo8NSObjectCSgSE_pKF in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSE6encode2toys7Encoder_p_tKFTq", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVSEAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSEAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleVSEAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadVSEAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0VSEAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferVyxGSEAASeRzSERzlMc in FirebaseCoreInternal(RingBuffer.o)
      _$s21FirebaseDatabaseSwift15ServerTimestampVSEAAMc in FirebaseDatabaseSwift(ServerTimestamp.o)
      ...
  "_$sSEMp", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVSEAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSEAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleVSEAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadVSEAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0VSEAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferVyxGSEAASeRzSERzlMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal10RingBufferVyxGSeAASeRzSERzlMc in FirebaseCoreInternal(RingBuffer.o)
      ...
  "_$sSH13_rawHashValue4seedS2i_tFTj", referenced from:
      _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFs17CodingUserInfoKeyV_Tg5 in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSH13_rawHashValue4seedS2i_tFTq", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSHAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0V10CodingKeys33_72A6A1068455B8734FAE5DFEDE1B0B2ELLOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferV10CodingKeys33_F496AD9081B84863A1C6F76A0399CD19LLOyx_GSHAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal12StorageErrorOSHAAMc in FirebaseCoreInternal(Storage.o)
      ...
  "_$sSH4hash4intoys6HasherVz_tFTj", referenced from:
      _$s21FirebaseDatabaseSwift15ServerTimestampV4hash4intoys6HasherVz_tF in FirebaseDatabaseSwift(ServerTimestamp.o)
      _$s21FirebaseDatabaseSwift15ServerTimestampV9hashValueSivg in FirebaseDatabaseSwift(ServerTimestamp.o)
      _$s21FirebaseDatabaseSwift15ServerTimestampVSHAASH4hash4intoys6HasherVz_tFTW in FirebaseDatabaseSwift(ServerTimestamp.o)
      _$s21FirebaseDatabaseSwift15ServerTimestampVSHAASH13_rawHashValue4seedS2i_tFTW in FirebaseDatabaseSwift(ServerTimestamp.o)
  "_$sSH4hash4intoys6HasherVz_tFTq", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSHAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0V10CodingKeys33_72A6A1068455B8734FAE5DFEDE1B0B2ELLOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferV10CodingKeys33_F496AD9081B84863A1C6F76A0399CD19LLOyx_GSHAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal12StorageErrorOSHAAMc in FirebaseCoreInternal(Storage.o)
      ...
  "_$sSH9hashValueSivgTq", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSHAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0V10CodingKeys33_72A6A1068455B8734FAE5DFEDE1B0B2ELLOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferV10CodingKeys33_F496AD9081B84863A1C6F76A0399CD19LLOyx_GSHAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal12StorageErrorOSHAAMc in FirebaseCoreInternal(Storage.o)
      ...
  "_$sSHMp", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSHAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0V10CodingKeys33_72A6A1068455B8734FAE5DFEDE1B0B2ELLOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferV10CodingKeys33_F496AD9081B84863A1C6F76A0399CD19LLOyx_GSHAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal12StorageErrorOSHAAMc in FirebaseCoreInternal(Storage.o)
      ...
  "_$sSHSQTb", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSHAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSHAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0V10CodingKeys33_72A6A1068455B8734FAE5DFEDE1B0B2ELLOSHAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal10RingBufferV10CodingKeys33_F496AD9081B84863A1C6F76A0399CD19LLOyx_GSHAAMc in FirebaseCoreInternal(RingBuffer.o)
      _$s20FirebaseCoreInternal12StorageErrorOSHAAMc in FirebaseCoreInternal(Storage.o)
      ...
  "_$sSKsSS7ElementRtzrlE6joined9separatorS2S_tF", referenced from:
      _$s19FirebaseSharedSwift0A11DataEncoderC19KeyEncodingStrategyO19_convertToSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZTf4nd_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZTf4nd_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSQ2eeoiySbx_xtFZTj", referenced from:
      _$sSasSQRzlE2eeoiySbSayxG_ABtFZ20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentF0V_Tg5Tf4nnd_n in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$sSasSQRzlE2eeoiySbSayxG_ABtFZ10Foundation4DateV_Tg5Tf4nnd_n in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s8Promises2eeoiySbAA5MaybeOyxG_AEtSQRzlF in PromisesSwift(Promise+Any.o)
      _$ss22__RawDictionaryStorageC4find_9hashValues10_HashTableV6BucketV6bucket_Sb5foundtx_SitSHRzlFs17CodingUserInfoKeyV_Tg5 in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s21FirebaseDatabaseSwift15ServerTimestampV2eeoiySbAC_ACtFZTf4nnd_n in FirebaseDatabaseSwift(ServerTimestamp.o)
  "_$sSQ2eeoiySbx_xtFZTq", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSQAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadVSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0VSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      ...
  "_$sSQMp", referenced from:
      _$s20FirebaseCoreInternal9HeartbeatVSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal10TimePeriodOSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal9HeartbeatV10CodingKeys33_892FDFB2EE9CA6459078D54BCB3472D2LLOSQAAMc in FirebaseCoreInternal(Heartbeat.o)
      _$s20FirebaseCoreInternal16HeartbeatsBundleV10CodingKeys33_DA2CD673DFB14EB4EF31ED1E0C34DBC6LLOSQAAMc in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadVSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentE0VSQAAMc in FirebaseCoreInternal(HeartbeatsPayload.o)
      ...
  "_$sSS10describingSSx_tclufC", referenced from:
      _$s8Promises7PromiseC11descriptionSSvg in PromisesSwift(Promise.o)
  "_$sSS14_fromSubstringySSSshFZ", referenced from:
      _$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZTf4nd_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSS18_uncheckedFromUTF8ySSSRys5UInt8VGFZ", referenced from:
      _$sSlsE10firstIndex5where0B0QzSgSb7ElementQzKXE_tKFSS_Tg5188$sSJSbs5Error_pIggdzo_SJSbsAA_pIegndzo_TR136$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZSbSJXEfU_Tf3npf_nTf1cn_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZTf4nd_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSS4hash4intoys6HasherVz_tF", referenced from:
      _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_20FirebaseCoreInternal13WeakContainerVyAF16HeartbeatStorageCGTg5 in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_Say10Foundation4DateVGTg5 in FirebaseCoreInternal(HeartbeatsBundle.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAASH9hashValueSivgTW in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAASH4hash4intoys6HasherVz_tFTW in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$s20FirebaseCoreInternal17HeartbeatsPayloadV10CodingKeysOSHAASH13_rawHashValue4seedS2i_tFTW in FirebaseCoreInternal(HeartbeatsPayload.o)
      _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFSS_Tg5 in FirebaseCoreInternal(HeartbeatStorage.o)
      _$ss17_NativeDictionaryV7_delete2atys10_HashTableV6BucketV_tFSS_20FirebaseCoreInternal13WeakContainerVyAI16HeartbeatStorageCGTg5 in FirebaseCoreInternal(HeartbeatStorage.o)
      ...
  "_$sSS5IndexV15characterStrideSiSgvg", referenced from:
      _$sSlsE10firstIndex5where0B0QzSgSb7ElementQzKXE_tKFSS_Tg5188$sSJSbs5Error_pIggdzo_SJSbsAA_pIegndzo_TR136$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZSbSJXEfU_Tf3npf_nTf1cn_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO21_convertFromSnakeCase33_6D166423BA39F764DCB8915CD73AA0F1LLyS2SFZTf4nd_n in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSS5IndexVMn", referenced from:
      _symbolic _____ SS5IndexV in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _symbolic Sny_____G SS5IndexV in FirebaseSharedSwift(FirebaseDataEncoder.o)
      _symbolic _____ySny_____GG s23_ContiguousArrayStorageC SS5IndexV in FirebaseSharedSwift(FirebaseDataEncoder.o)
  "_$sSS5countSivg", referenced from:
      _$s10Foundation4DataV20FirebaseCoreInternalE16base64URLEncoded7optionsACSgSS_So27NSDataBase64DecodingOptionsVtcfC in FirebaseCoreInternal(HeartbeatsPayload.o)
  "_$sSS5index5afterSS5IndexVAD_tF", referenced from:
      
```

</details>

**Comment by marchbold** [comment]
> @ajwfrost Sorry for the delay in getting back to you on this one.
> 
> We have been able to confirm that an application running on iOS 12.5.5 built with AIR 50.2.3.5 was crashing with
>
> ```
> Exception Type:  EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note:  EXC_CORPSE_NOTIFY
> Termination Description: DYLD, Symbol not found: _$s10Foundation10CocoaErrorV4CodeVAA01_cD8ProtocolAAMc
> ```
>
> Updating with the adt.jar from the comment resolved the issue!
> 
> It is also working with this updated adt on more recent versions including iOS 16.6


However , still getting the issue with the simulator. I'm guessing we need an alternative path  here for the swift libs, not sure if this is something we can add to the platform options?

**Comment by ajwfrost** [comment]
Hi @marchbold  - just to confirm, when you tried the above that crashed with the 'symbol not found' issue, was that with the ANE that had the "-lswiftFoundation' option added in platform options file? I thought we'd found that the missing symbol was resolved with this, without needing the rearrangement of the linker order..

We'll take a look at the simulator here, it sounds like an extra change to ADT is needed.

**Comment by marchbold** [comment]
@ajwfrost So the `-lswiftFoundation` resolved it for recent versions of iOS however we have had lots of reports from users on older iOS versions (12-15 I believe) that were still encountering a related issue (i.e. a crash on launch with something like the above error). 

However using the `-lswiftFoundation` flag and the `adt.jar` from above seems to have resolved that .

**Comment by shaymolho** [comment]
Hi @ajwfrost,

We also encountered the issue with the simulator (#2851),

@ajwfrost, 
Do you have an update for that?

**Comment by ajwfrost** [comment]
Hi - I just saw the fix for this one get submitted in our repository.. let me get a build kicked off and I'll post an interim update here later on today.

thanks

**Comment by takazawa-gg** [comment]
I am facing this very problem right now.

In our app we introduced Distriqt PushNotification ANE and now it crashes when launching the app on devices under iOS 15.
It can be launched on iOS 16,17.

Is this symptom going to be fixed in a new AIR SDK release?
If so, is it available at the same time as the workaround in #2772?

We apologize for the trouble, but we would appreciate your confirmation.

**Comment by ajwfrost** [comment]
Hi

So we're currently building an update of ADT that will include:
- fix for the failure to find swift libraries (when using platformsdk option, and/or ios simulator variants)
- fix for the crash per the original issue here (where an ANE update had resolved it for iOS 16+ but we needed the additional ADT update to the linker command-line in order to fix it for iOS 15 and below)
- updated Android handling of the window focus event to provide the activate/deactivate AS3 notifications (i.e. per the interim update to adt provided under #2772)

We'll release this formally at the end of the week all being well, but I'll post the jar file here too.

thanks

**Comment by ajwfrost** [comment]
Updated ADT.jar file is within the below zip...
[adt.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12741206/adt.zip)

thanks

**Comment by shaymolho** [comment]
Hi @ajwfrost 

Running the simulator build with the new adt.jar resulted with the following error:

```
Warning: The path to platform sdk should end with any one of the (iPhoneOSx.x | iPhoneSimulatorx.x | AppleTVSimulatorx.x | AppleTVOSx.x) format to avoid any unintended behavior.
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(Heartbeat.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsBundle.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatStorage.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseSessions, __swift_FORCE_LOAD_$_swiftCompatibility50_$_Promises , __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseSharedSwift , __swift_FORCE_LOAD_$_swiftCompatibility50_$_FirebaseCoreInternal )
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(Heartbeat.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsBundle.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatStorage.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_Promises, __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseSessions , __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseSharedSwift , __swift_FORCE_LOAD_$_swiftCompatibility51_$_FirebaseCoreInternal )
  "__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(Heartbeat.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsBundle.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatStorage.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseSharedSwift, __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_Promises , __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseSessions , __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseCoreInternal )
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(Heartbeat.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatController.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsBundle.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatsPayload.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal in FirebaseCoreInternal(HeartbeatStorage.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseSharedSwift, __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_Promises , __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseCoreInternal , __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_FirebaseSessions )
ld: symbol(s) not found for architecture x86_64

```

**Comment by marchbold** [comment]
@shaymolho Beat me to it, I was just about to post that same thing. 



@ajwfrost Here's the ld command line:

`
ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch x86_64 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk" -L/usr/lib -L/usr/lib/swift -F"/System/Library/Frameworks" -L"/Users/marchbold/work/sdks/air/AIRSDK_50.2.3/lib/aot/lib" -o "../aot3508174828252961816.tmp" -x "/Users/marchbold/work/sdks/air/AIRSDK_50.2.3/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a" -lc++ -lSystem -U ___darwin_check_fd_set_overflow -lz -lobjc -lclang_rt.ios -lclang_rt.ios -ObjC -weak_framework UserNotifications -w "-F/var/folders/tb/mhsb9xwj7kgbbtsjrcm3f5w40000gn/T/95b64c0b-91c0-4924-b8d1-23732a266dc4" -framework "CoreNativeExtension" -rpath /usr/lib/swift -lswiftFoundation -lSwiftCompat -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData -framework "FBLPromises" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesSwift" -framework "FirebaseSharedSwift" -framework "FirebaseAnalytics" -filelist "/Users/marchbold/work/distriqt/extensions/extensions/firebase/source/extensions/core/example/starling/bin-debug/AOTBuildOutput3962210148671325413.tmp/OBJFilesList.txt" -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -platform_version ios-simulator 11.0 16.4 -exported_symbols_list "/Users/marchbold/work/distriqt/extensions/extensions/firebase/source/extensions/core/example/starling/bin-debug/AOTBuildOutput3962210148671325413.tmp/SYMFilesList.txt"
`

I can get it to run by copying the following files into `AIRSDK/lib/aot/lib` from `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator`

- `libswiftCompatibility50.a`
- `libswiftCompatibility51.a`
- `libswiftCompatibility56.a`
- `libswiftCompatibilityDynamicReplacements.a`
- `libswiftConcurrency.a`

**Comment by marchbold** [comment]
(iOS 12-15 seems to be working with this one so same result there).

**Comment by ajwfrost** [comment]
Okay thanks - we'd better address that simulator swift linking issue..

> (iOS 12-15 seems to be working with this one so same result there).

Just to check, does this mean the crash-on-startup reported under https://github.com/distriqt/ANE-Firebase/issues/462 looks like it's fixed with this update to ADT in conjunction with your latest ANE update?

thanks

**Comment by marchbold** [comment]
Yep, that one should be resolved with this update. Just the simulator issue now

**Comment by ajwfrost** [comment]
So currently there's the "libSwiftCompat.a" archive in the SDK 'lib' folder, and I'm assuming your ANE will be including the `-lSwiftCompat` additional command should it need this? But this didn't help in terms of the Simulator build, because that archive only had the arm64 files in it...

Below is a zip that contains an updated version of libSwiftCompat.a which is a fat/universal file with arm64 and x86_64 versions, if you unzip this into the SDK lib/aot/lib folder, and try again, I would hope this time it works..!

thanks
[swiftCompat.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12749860/swiftCompat.zip)

**Comment by marchbold** [comment]
Bingo! Looks good with that addition :) 

(Yep our ANEs that rely on this have the `-lSwiftCompat` option, should see it in the command line I posted above)

**Comment by shaymolho** [comment]
Hey @ajwfrost,

Maybe it's a different issue i don't understand ,
but now running the simulator build failed on the following error:
`Failure in codesign request`
The same build not for simulator succeed

(By The way, where can i find the adt.log file? can't find it in the user home dir)

Thanks

**Comment by ajwfrost** [comment]
Curious one .. the adt.log file should be under /Users/username/adt.log but only if you've configured this to appear, by adding a line "DebugOut=true" to a file /Users/username/.airsdk/adt.cfg.
Or the simpler option: use the AIR SDK Manager (where you can tick a box to set up the logging, or you can just go to the "Troubleshooting" pane and ADT will magically log to this area...

thanks

**Comment by raresn** [comment]
@marchbold Our issue on #2860 is the same as @takazawa-gg described! (Can't run on ios < 16)
Problem is that we have it live on AppStore.
You can change AppStore to Romania, and download https://apps.apple.com/ro/app/ontimeagenda/id1327348934

**Comment by shaymolho** [comment]
Hi @ajwfrost ,

As I wrote now the simulator build fails on this error:
`Failure in codesign request
`

I'm attching the adt.log from this build:
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/12777074/adt.log)

The same build with 'ipa-debug' target works.

I don't know how to proceed from here,
Your help is much needed.

Thanks

**Comment by shaymolho** [comment]
Hi @ajwfrost, 

Waiting for your response.

Thanks

**Comment by ajwfrost** [comment]
Hi @shaymolho  - we're not able to reproduce that here and the log file doesn't really suggest much happening on the code-signing front! A couple of options perhaps:
* can you try editing the adt.cfg file and uncommenting/adding the line: `UseNativeCodesign=true`
* alternatively can you just remove the signing arguments from your command-line? Simulator builds don't need to be code-signed I believe...


thanks

**Comment by shaymolho** [comment]
HI @ajwfrost , 

I did both things and it didn't work.
I also tried to upgrade to the latest AIR 50 version. This didn't work either.

We need this app in simulator mode, 
and it just doesn't work.

What can i do now?

**Comment by shaymolho** [comment]
@ajwfrost maybe u can add more logging to pinpoint the codesign issue?

**Comment by shaymolho** [comment]
@ajwfrost reminder
we cannot build simulator right now

**Comment by ajwfrost** [comment]
Hi - thanks for the reminder, we can put together an ADT version with some additional logging per your suggestion; to start with though are you able to enable debugging and confirm what it says in terms of the command-line for the code signing? The simplest way to do this is to have the AIR SDK Manager installed, and open this to the "Troubleshooting" page?

thanks

**Comment by mrfrasier** [comment]
Just found this thread. Users of our live app are reporting crashes when on older iOS versions. We don't have an older iOS device here to test with, but so I understand, do we need to do the following?

- Overlay adt.jar into current SDK (we're using 50.2.3.6
- add the lswiftFoundation and lSwiftCompat options to our xml
- overlay libSwiftCompat.a file @ajwfrost linked above

Then we're golden?

Separately, @marchbold I see you linked a test version of Firebase up there. Could this also solve the issues I've had (and reported elsewhere) building the app for iOS with Firebase included?

Thanks guys

**Comment by ajwfrost** [comment]
Hi @mrfrasier  - the changes from above for ADT and libSwiftCompat.a should be in 50.2.3.6 already, so in terms of the crash on older iOS versions, that should have been fixed by that (iirc, a re-ordering of the libraries/frameworks that we link against..)

thanks

**Comment by mrfrasier** [comment]
> Hi @mrfrasier - the changes from above for ADT and libSwiftCompat.a should be in 50.2.3.6 already, so in terms of the crash on older iOS versions, that should have been fixed by that (iirc, a re-ordering of the libraries/frameworks that we link against..)
> 
> thanks

Thanks for the reply. My app is actually built with 2.3.6 with the updated overlay files as that solved another issue I was having, but my users still report that the app crashes right back out on iOS versions under 16. I did manage to get my hands on a device and witnessed the same behavior sadly.

What data can I provide to help track down the issue?

**Comment by ajwfrost** [comment]
If you're able to get the crash report it would be handy .. Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data, then you'll see a long list of crash reports, if you find yours by process name (filename from the app descriptor file) there's a "send to" option at the top right of the screen.

thanks

**Comment by mrfrasier** [comment]
> If you're able to get the crash report it would be handy .. Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data, then you'll see a long list of crash reports, if you find yours by process name (filename from the app descriptor file) there's a "send to" option at the top right of the screen.
> 
> thanks

Hi Andrew, please see attached
[Crash-Log.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13267234/Crash-Log.zip)

**Comment by ajwfrost** [comment]
Thanks .. that does look similar to the issue we were getting with the out-of-order linking, although not a symbol/library that I recognise:
```
Termination Description: DYLD, Symbol not found: _$sSS10FoundationE19_bridgeToObjectiveCSo8NSStringCyF | Referenced from: exe_file | Expected in: dyld shared cache
```

But again with "Foundation" which is the issue we had earlier, where symbols were expected to be in Foundation but weren't. This may be the other way round..! Did you build this on Windows, or macOS? And are you able to provide the ld64 command line (if you use the SDK Manager Troubleshooting tab, when packaging the IPA file it should display this line..)?

**Comment by mrfrasier** [comment]
Yup, on Windows here. here is the ld64 command (this build fails because I'm simultaneously trying to figure out a Firebase issue with Michael and that problematic ANE is present, but figured you just needed to see the general command) This is on 50.2.3.7

`ld64 command line: E:\AIR\50.2.3.7\lib\aot/bin/ld64/ld64.exe -pie -ObjC -dead_strip -Z -arch arm64 -L"E:\\AIR\\50.2.3.7\\lib\\aot/stub" -F"E:\\AIR\\50.2.3.7\\lib\\aot/stub" -L"E:\\AIR\\50.2.3.7\\lib\\aot/lib" -o "../aot13033722365762679605.tmp" -x "E:\\AIR\\50.2.3.7\\lib\\aot/lib/libRuntimeHMAOT.arm-air.a" "E:\\AIR\\50.2.3.7\\lib\\aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lz -lobjc -lclang_rt.ios -weak_framework AppTrackingTransparency -framework AdSupport -w -liconv -framework QuartzCore -weak_framework CoreVideo -weak_framework CoreMedia -weak_framework AVFoundation -w "-FE:\\tmp\\d783b3cb-cd20-45f6-8a9a-f2068b4bdee5" -framework "Bolts" -rpath /usr/lib/swift -lswiftFoundation -lSwiftCompat -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData -framework "FBLPromises" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesSwift" -framework "FirebaseSharedSwift" -weak_framework Photos -framework AssetsLibrary -w -rpath @executable_path/Frameworks -weak_framework VideoToolbox -weak_framework WebKit -framework UIKit -weak_framework SystemConfiguration -weak_framework Social -weak_framework Security -weak_framework SafariServices -weak_framework LocalAuthentication -weak_framework CoreTelephony -weak_framework CoreLocation -weak_framework CoreMotion -framework CoreMedia -framework CoreImage -framework CoreGraphics -framework CFNetwork -framework AVFoundation -framework AudioToolbox -lc++ -lxml2 -lz -ObjC -framework "ISFacebookAdapter" -framework "FBAudienceNetwork" -rpath /usr/lib/swift -lSwiftCompat -framework WebKit -framework Network -framework Foundation -framework CryptoKit -framework CoreMotion -lz -w -framework "ISUnityAdsAdapter" -framework "UnityAds" -rpath /usr/lib/swift -lswiftFoundation -lSwiftCompat -framework "IronSource" -w -framework MessageUI -framework Accounts -framework Social -framework ImageIO -w -framework "FirebaseAnalytics" -w -lsqlite3 -ObjC -weak_framework iAd -framework JavaScriptCore -framework GLKit -framework SafariServices -framework MediaPlayer -framework CoreVideo -w -framework "GoogleAppMeasurementIdentitySupport" -framework "GoogleMobileAds" -framework "PromisesObjC" -framework "UserMessagingPlatform" -framework "ISAdMobAdapter" -framework PhotosUI -framework Photos -w -weak_framework SwiftUI -weak_framework Combine -framework UserNotifications -framework AddressBook -framework "FirebaseABTesting" -framework "FirebaseInAppMessaging" -framework "FirebaseInAppMessagingSwift" -framework "FirebaseMessaging" -lclang_rt.ios -ObjC -weak_framework UserNotifications -w -framework "CoreNativeExtension" -w -framework "AppLovinSDK" -framework "ISAppLovinAdapter" -w -framework AuthenticationServices -filelist "e:\\Projects\\Makazu\\appdev\\app-apm\\bin\\AOTBuildOutput6309088063484373593.tmp\\OBJFilesList.txt" -framework CoreFoundation -framework MobileCoreServices -framework OpenGLES -framework CoreLocation -framework GameController -platform_version ios 11.0 16.4 -exported_symbols_list "e:\\Projects\\Makazu\\appdev\\app-apm\\bin\\AOTBuildOutput6309088063484373593.tmp\\SYMFilesList.txt"
`

**Comment by ajwfrost** [comment]
Hi

So that missing symbol appears a few times online, seems to have caused a number of issues.. but to try to work out where it would come from: we have it in three places in the latest iPhone SDK:
- /usr/lib/libextension.tbd
- /usr/lib/swift/libswiftFoundation.tbd
- /System/Library/Frameworks/Foundation.framework/Foundation.tbd

In the binary above, it seems to be looking for it in the dyld cache.. 
The linker arguments suggest it should look first in libswiftFoundation before the Foundation framework, and there's no mention of the "extension" library in the build command. But each of the references have also got ios-version specific annotations...

This may be something related to how we're handling these TBD files and turning them into libraries, potentially we're seeing them coming from the wrong place. You're both using Windows to compile this, do you have any access to a mac to try that? I would be interested in the results both with and without the `-platformsdk` option.

In terms of reproducing this: do you know if it's 100% reproducible, with the binaries you've built on Windows, when using the older (iOS 15 and earlier) versions? Also, I don't think we've ever got a reproduction scenario so is there any chance we could get a set of files (XML/SWF/ANEs) so that we can package it and test it here to reproduce the problem?

We have a potential workaround, although a lot of that may depend on whether it also fails if you built it on a macOS machine using the `-platformsdk` argument, and it may then mean we have to be creative when it comes to distributing some of the SDK components that are subject to third party agreements.. 

If you can help with a reproduction - either by sending us your app files, or by trying something out for us if you're able to reproduce things there - then please email me, andrew dot frost at harman dot com..

thanks

**Comment by Mintonist** [comment]
Can production version of app help you? You will see crashes on old IOS versions.
Or I can send you all used ANEs.

**Comment by ajwfrost** [comment]
As long as it's in a form that we can package up an IPA from it .. but just getting an IPA is probably of limited value as we'd not be able to do much to tweak the settings and try to reproduce and then fix it..
A list of ANEs could be helpful though. We'd used the "com.distriqt.Bolt" one as I thought that had got some Swift dependencies in it which may have triggered this issue..

**Comment by Mintonist** [comment]
@ajwfrost,   [IPA and all ANEs files](https://disk.yandex.ru/d/BSXBEVs3CgqWSA)

**Comment by marchbold** [comment]
@Mintonist Please do not distribute our ANEs on public forums.
